### ISSUE TITLE
trees.obj

### ISSUE THREAD

**Issue by leocala** [sybrexsys/llPDFLib#2]
greetings, I downloaded llpdflib, indeed I am not able to compile the code because trees.obj is missing. can you help me out on this matter? thanks

**Comment by sad66** [comment]
Trees.obj is a part. It is Sources \ obj folder 31.01.2017, 19:05, "leocala" <notifications@github.com>:greetings, I downloaded llpdflib, indeed I am not able to compile the code because trees.obj is missing. can you help me out on this matter? thanks—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sybrexsys** [comment]
What delphi version are you use?
